module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],

  
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       'mdx',
  //       {
  //         type: 'category',
  //         label: 'Docs',
  //         items: ['doc1', 'doc2', 'doc3'],
  //       },
  //     ],
  //   },
  // ],



  // someSidebar: {
  //   Docusaurus: ['doc1', 'doc2', 'doc3'],
  //   Features: ['mdx'],
  // },
};
