import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/zh-cn/blog',
    component: ComponentCreator('/zh-cn/blog', '16e'),
    exact: true
  },
  {
    path: '/zh-cn/blog/archive',
    component: ComponentCreator('/zh-cn/blog/archive', 'ae5'),
    exact: true
  },
  {
    path: '/zh-cn/blog/tags',
    component: ComponentCreator('/zh-cn/blog/tags', 'a76'),
    exact: true
  },
  {
    path: '/zh-cn/blog/tags/docusaurus-v-2',
    component: ComponentCreator('/zh-cn/blog/tags/docusaurus-v-2', 'd04'),
    exact: true
  },
  {
    path: '/zh-cn/blog/tags/hello',
    component: ComponentCreator('/zh-cn/blog/tags/hello', '4ee'),
    exact: true
  },
  {
    path: '/zh-cn/blog/welcome-docusaurus-v2',
    component: ComponentCreator('/zh-cn/blog/welcome-docusaurus-v2', 'c65'),
    exact: true
  },
  {
    path: '/zh-cn/docs',
    component: ComponentCreator('/zh-cn/docs', '60e'),
    routes: [
      {
        path: '/zh-cn/docs/IIT',
        component: ComponentCreator('/zh-cn/docs/IIT', '7f0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/IIT/doc2',
        component: ComponentCreator('/zh-cn/docs/IIT/doc2', 'c2b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/IIT/doc3',
        component: ComponentCreator('/zh-cn/docs/IIT/doc3', '4ab'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/Quaddle',
        component: ComponentCreator('/zh-cn/docs/Quaddle', 'ff9'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/Quaddle2.0/quaddle_02',
        component: ComponentCreator('/zh-cn/docs/Quaddle2.0/quaddle_02', 'cb1'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/Quaddle2.0/quaddle_03',
        component: ComponentCreator('/zh-cn/docs/Quaddle2.0/quaddle_03', 'dad'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/Quaddle2.0/quaddle_04',
        component: ComponentCreator('/zh-cn/docs/Quaddle2.0/quaddle_04', '8c7'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/Quaddle2.0/quaddle_05',
        component: ComponentCreator('/zh-cn/docs/Quaddle2.0/quaddle_05', 'ea6'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/SL',
        component: ComponentCreator('/zh-cn/docs/SL', '2d9'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/test/doc1',
        component: ComponentCreator('/zh-cn/docs/test/doc1', '1f2'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/test/doc2',
        component: ComponentCreator('/zh-cn/docs/test/doc2', 'e82'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/test/doc3',
        component: ComponentCreator('/zh-cn/docs/test/doc3', 'fe8'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/test/mdx',
        component: ComponentCreator('/zh-cn/docs/test/mdx', '678'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/zh-cn/docs/test/mdx3',
        component: ComponentCreator('/zh-cn/docs/test/mdx3', '425'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '/zh-cn/',
    component: ComponentCreator('/zh-cn/', '26b'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
