import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/blog',
    component: ComponentCreator('/blog', 'f05'),
    exact: true
  },
  {
    path: '/blog/archive',
    component: ComponentCreator('/blog/archive', '182'),
    exact: true
  },
  {
    path: '/blog/tags',
    component: ComponentCreator('/blog/tags', '287'),
    exact: true
  },
  {
    path: '/blog/tags/docusaurus-v-2',
    component: ComponentCreator('/blog/tags/docusaurus-v-2', '49f'),
    exact: true
  },
  {
    path: '/blog/tags/hello',
    component: ComponentCreator('/blog/tags/hello', '28f'),
    exact: true
  },
  {
    path: '/blog/welcome-docusaurus-v2',
    component: ComponentCreator('/blog/welcome-docusaurus-v2', '5bf'),
    exact: true
  },
  {
    path: '/docs',
    component: ComponentCreator('/docs', 'e26'),
    routes: [
      {
        path: '/docs',
        component: ComponentCreator('/docs', 'e40'),
        routes: [
          {
            path: '/docs',
            component: ComponentCreator('/docs', '2d4'),
            routes: [
              {
                path: '/docs/IIT',
                component: ComponentCreator('/docs/IIT', '799'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/IIT/doc2',
                component: ComponentCreator('/docs/IIT/doc2', '636'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/IIT/doc3',
                component: ComponentCreator('/docs/IIT/doc3', '342'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/Quaddle',
                component: ComponentCreator('/docs/Quaddle', 'c75'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/Quaddle2.0/quaddle_02',
                component: ComponentCreator('/docs/Quaddle2.0/quaddle_02', '51b'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/Quaddle2.0/quaddle_03',
                component: ComponentCreator('/docs/Quaddle2.0/quaddle_03', 'be9'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/Quaddle2.0/quaddle_04',
                component: ComponentCreator('/docs/Quaddle2.0/quaddle_04', '112'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/Quaddle2.0/quaddle_05',
                component: ComponentCreator('/docs/Quaddle2.0/quaddle_05', '8a5'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/SL',
                component: ComponentCreator('/docs/SL', '8ae'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/test/doc1',
                component: ComponentCreator('/docs/test/doc1', '870'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/test/doc2',
                component: ComponentCreator('/docs/test/doc2', 'f58'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/test/doc3',
                component: ComponentCreator('/docs/test/doc3', '858'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/test/mdx',
                component: ComponentCreator('/docs/test/mdx', '522'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/test/mdx3',
                component: ComponentCreator('/docs/test/mdx3', '146'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '/',
    component: ComponentCreator('/', '2e1'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
