import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/blog',
    component: ComponentCreator('/blog', '6a2'),
    exact: true
  },
  {
    path: '/blog/archive',
    component: ComponentCreator('/blog/archive', '7fe'),
    exact: true
  },
  {
    path: '/blog/tags',
    component: ComponentCreator('/blog/tags', '375'),
    exact: true
  },
  {
    path: '/blog/tags/docusaurus-v-2',
    component: ComponentCreator('/blog/tags/docusaurus-v-2', '5c6'),
    exact: true
  },
  {
    path: '/blog/tags/hello',
    component: ComponentCreator('/blog/tags/hello', 'be3'),
    exact: true
  },
  {
    path: '/blog/welcome-docusaurus-v2',
    component: ComponentCreator('/blog/welcome-docusaurus-v2', '083'),
    exact: true
  },
  {
    path: '/docs',
    component: ComponentCreator('/docs', 'cc3'),
    routes: [
      {
        path: '/docs/IIT',
        component: ComponentCreator('/docs/IIT', 'f4c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/IIT/doc2',
        component: ComponentCreator('/docs/IIT/doc2', '819'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/IIT/doc3',
        component: ComponentCreator('/docs/IIT/doc3', '190'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/Quaddle',
        component: ComponentCreator('/docs/Quaddle', 'b41'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/Quaddle2.0/quaddle_02',
        component: ComponentCreator('/docs/Quaddle2.0/quaddle_02', '6c9'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/Quaddle2.0/quaddle_03',
        component: ComponentCreator('/docs/Quaddle2.0/quaddle_03', '5ae'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/Quaddle2.0/quaddle_04',
        component: ComponentCreator('/docs/Quaddle2.0/quaddle_04', '6a0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/Quaddle2.0/quaddle_05',
        component: ComponentCreator('/docs/Quaddle2.0/quaddle_05', 'f25'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/SL',
        component: ComponentCreator('/docs/SL', 'b6b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/test/doc1',
        component: ComponentCreator('/docs/test/doc1', '010'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/test/doc2',
        component: ComponentCreator('/docs/test/doc2', 'c87'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/test/doc3',
        component: ComponentCreator('/docs/test/doc3', 'a79'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/test/mdx',
        component: ComponentCreator('/docs/test/mdx', '04e'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/test/mdx3',
        component: ComponentCreator('/docs/test/mdx3', 'f75'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '/',
    component: ComponentCreator('/', 'd4a'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
